{
 "title": "ML API Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  kube_pod_info{\n    namespace=\"ml-api\",\n    pod=~\"ml-api-.*\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inference Velocity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(prediction_requests_total[1m]))",
     "legendFormat": "Avg. Req/Sec"
    }
   ]
  },
  {
   "title": "Success Ratio",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prediction_requests_total) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "95th Percentile Latency"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"ml-api-.*\"}[1m]))",
     "legendFormat": "Cumulative Core-Seconds"
    }
   ]
  }
 ]
}